import { z } from "zod"
import { resolveSessionForTool, getReadySessionId } from "../session/ensure.js"
import { isSessionOrError } from "./core/response.js"
import { ACCESS_TOKEN_SCHEMA } from "./core/access-token.js"
import { defineTool } from "./core/define-tool.js"
import { toolOk, toolError } from "./core/response.js"
import { executeSqlPipeline } from "./execute-sql.pipeline.js"
import type { McpToolResult } from "./core/types.js"

export const ExecuteSqlInputSchema = z.object({
  session_id: z.string().optional().describe("Session ID from connect (optional if access_token set)"),
  access_token: z.string().optional().describe("JWT from connect — preferred on hosted Vercel"),
  sql: z.string().min(1).describe("SELECT query to execute — generated by the AI client"),
  database_url: z.string().optional().describe("Postgres URL — only on first connect or legacy mode"),
})

export type ExecuteSqlInput = z.infer<typeof ExecuteSqlInputSchema>

const inputSchema = {
  type: "object" as const,
  properties: {
    session_id: { type: "string", description: "Session ID from connect" },
    access_token: ACCESS_TOKEN_SCHEMA,
    sql: {
      type: "string",
      description: "A SELECT query. No INSERT/UPDATE/DELETE/DDL — those are blocked.",
    },
    database_url: {
      type: "string",
      description: "Optional Postgres URL for serverless reconnect",
    },
  },
  required: ["sql"],
}

async function handleExecuteSql(args: ExecuteSqlInput): Promise<McpToolResult> {
  const resolved = await resolveSessionForTool(
    args.session_id,
    args.database_url,
    args.access_token,
  )
  if (isSessionOrError(resolved)) return resolved
  const session = resolved

  try {
    const result = await executeSqlPipeline(args.sql, getReadySessionId(session), session)

    const lines = [
      result.cached
        ? `✓ Cached result (${result.durationMs}ms)`
        : `✓ Executed in ${result.durationMs}ms`,
      result.truncated
        ? `⚠ Truncated to ${result.rowCount} rows (more exist)`
        : `${result.rowCount} row${result.rowCount !== 1 ? "s" : ""}`,
      "",
      JSON.stringify(result.rows, null, 2),
    ]

    return toolOk(lines.join("\n"))
  } catch (err) {
    return toolError(err instanceof Error ? err.message : String(err))
  }
}

export const executeSqlTool = defineTool({
  name: "execute_sql",
  description: `Run a validated SELECT query on the user's database. Pass access_token from connect.
Server validates SQL (blocks writes/DDL), executes read-only, returns JSON rows.`,
  inputSchema,
  meta: { "x-openai-isConsequential": false },
  handler: handleExecuteSql,
})

/** @deprecated Use executeSqlTool */
export const queryTool = executeSqlTool

export { handleExecuteSql }
