import { z } from "zod"
import { getSession, getSessionForDatabaseUrl } from "../session/manager.js"
import { config } from "../config/index.js"
import { defineTool } from "./core/define-tool.js"
import { toolOk, toolError } from "./core/response.js"
import { executeSqlPipeline } from "./execute-sql.pipeline.js"
import type { McpToolResult } from "./core/types.js"

export const ExecuteSqlInputSchema = z.object({
  session_id: z.string().describe("Session ID from connect"),
  sql: z.string().min(1).describe("SELECT query to execute — generated by the AI client"),
})

export type ExecuteSqlInput = z.infer<typeof ExecuteSqlInputSchema>

const inputSchema = {
  type: "object" as const,
  properties: {
    session_id: { type: "string", description: "Session ID from connect" },
    sql: {
      type: "string",
      description: "A SELECT query. No INSERT/UPDATE/DELETE/DDL — those are blocked.",
    },
  },
  required: ["session_id", "sql"],
}

async function handleExecuteSql(args: ExecuteSqlInput): Promise<McpToolResult> {
  let session = getSession(args.session_id)
  if (!session) {
    try {
      session = getSessionForDatabaseUrl(config.DATABASE_URL)
    } catch {
      // no DATABASE_URL in this context
    }
  }
  if (!session) return toolError("Session not found or expired. Call 'connect' first.")
  if (session.status !== "ready") {
    return toolError(`Session not ready: ${session.status}. Wait for connect to complete.`)
  }

  try {
    const result = await executeSqlPipeline(args.sql, args.session_id, session)

    const lines = [
      result.cached
        ? `✓ Cached result (${result.durationMs}ms)`
        : `✓ Executed in ${result.durationMs}ms`,
      result.truncated
        ? `⚠ Truncated to ${result.rowCount} rows (more exist)`
        : `${result.rowCount} row${result.rowCount !== 1 ? "s" : ""}`,
      "",
      JSON.stringify(result.rows, null, 2),
    ]

    return toolOk(lines.join("\n"))
  } catch (err) {
    return toolError(err instanceof Error ? err.message : String(err))
  }
}

export const executeSqlTool = defineTool({
  name: "execute_sql",
  description: `Execute a SQL SELECT query against the connected database.

The AI client (you) should:
1. First call schema_reader to understand the table structure
2. Generate the appropriate SELECT query based on the user's question
3. Call this tool with that SQL

The server will:
- Validate the SQL (block writes, DDL, injection attempts)
- Check the LRU cache (identical queries return instantly)
- Execute in a READ ONLY transaction with timeout + row limit
- Strip PII columns from results
- Return rows as JSON`,
  inputSchema,
  handler: handleExecuteSql,
})

/** @deprecated Use executeSqlTool */
export const queryTool = executeSqlTool

export { handleExecuteSql }
